import type { Metadata } from 'next';
import { Inter, Roboto } from 'next/font/google';
import './globals.css';
import TanStackProvider from '@/configs/providers/TanStackProvider';
// const inter = Inter({ subsets: ['vietnamese'] });
const roboto = Roboto({ subsets: ['vietnamese'], weight: ['400'] });

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={roboto.className}>
        <TanStackProvider>{children}</TanStackProvider>
      </body>
    </html>
  );
}
